### ISSUE TITLE
no replset config has been received

### ISSUE THREAD

**Issue by PuKoren** [morphy2k/k8s-mongo-sidecar#1]
I have a `no replset config has been received` message when I try to deploy the cluster on my K8s. I don't know why it happens. Here is my Yaml:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: production
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
  namespace: production
spec:
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
        environment: production
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
            - "--replSet=rs0"
            - "--smallfiles"
            - "--noprealloc"
            - "--bind_ip=0.0.0.0"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
          resources:
            requests:
              memory: "1G"
              cpu: "0.5"
            limits:
              memory: "2G"
              cpu: "2"
        - name: mongo-sidecar
          image: morphy/k8s-mongo-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo,environment=production"
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "ssd"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 25Gi
```

Is there anything I obviously did wrong ?

Thanks for your help

```js
rs.status()
{
	"operationTime" : Timestamp(0, 0),
	"ok" : 0,
	"errmsg" : "no replset config has been received",
	"code" : 94,
	"codeName" : "NotYetInitialized"
}
```

**Comment by morphy2k** [comment]
There are a few minor differences in the configuration of this fork.
The environment variable `MONGO_SIDECAR_POD_LABELS` is here `KUBERNETES_POD_LABELS`.

Take a look at the example directory. https://github.com/morphy2k/k8s-mongo-sidecar/blob/master/example/mongo-statefulset.yaml

**Comment by PuKoren** [comment]
Ha I see ! Sorry taking your time. Thanks for the sidecar :+1:

**Comment by wlopez-cl** [comment]
Same as @PuKoren with this yaml file.

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
spec:
  serviceName: mongo
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:4
          command:
            - mongod
          args:
            - '--replSet=rs0'
            - '--bind_ip=0.0.0.0'
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
        - name: mongo-sidecar
          image: morphy/k8s-mongo-sidecar
          env:
            - name: KUBERNETES_POD_LABELS
              value: 'role=mongo, environment=test'
            - name: KUBERNETES_SERVICE_NAME
              value: 'mongo'
  selector:
    matchLabels:
      role: mongo
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: do-block-storage
```
