### ISSUE TITLE
mongo pod not receiving configuration for master and secondary

### ISSUE THREAD

**Issue by jmndao** [morphy2k/k8s-mongo-sidecar#216]
I was following the example to configure a statefulset deployment, however, with my actual config I'm seeing the pod running 2/2 but when I connect to the first replica I'm expecting to it being master, in my case, it's not.
I'm using minikube.

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: auth-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
# # RBAC for Auth
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
---
# # Stateful Config
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-mongo
spec:
  selector:
    matchLabels:
      role: auth-mongo
      app: auth-mongo
  serviceName: "auth-mongo-srv"
  replicas: 2
  template:
    metadata:
      labels:
        app: auth-mongo
        role: auth-mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: auth-mongo
          image: mongo
          command:
            - mongod
            - "--bind_ip_all"
            - "--replSet"
            - rs0
          ports:
            - containerPort: 27017
              name: auth-db
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/auth-db
        - name: auth-mongo-sidecar
          image: morphy/k8s-mongo-sidecar
          env:
            - name: KUBERNETES_POD_LABELS
              value: "app=auth-mongo,environment=test"
            - name: KUBERNETES_SERVICE_NAME
              value: "auth-mongo-srv"
  volumeClaimTemplates:
    - metadata:
        name: mongo-storage
        annotations:
          volume.beta.kubernetes.io/storage-class: "auth-storage"
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
# # Auth Service
apiVersion: v1
kind: Service
metadata:
  name: auth-mongo-srv
spec:
  selector:
    app: auth-mongo
  ports:
    - name: auth-db
      protocol: TCP
      port: 27017
      targetPort: 27017

````

This is the ouput for `kubectl exec -ti auth-mongo-0 --mongosh`
```
Defaulted container "auth-mongo" out of: auth-mongo, auth-mongo-sidecar
Current Mongosh Log ID:	6395d4f683739afc691b67a4
Connecting to:		mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.6.1
Using MongoDB:		6.0.3
Using Mongosh:		1.6.1

For mongosh info see: https://docs.mongodb.com/mongodb-shell/


To help improve our products, anonymous usage data is collected and sent to MongoDB periodically (https://www.mongodb.com/legal/privacy-policy).
You can opt-out by running the disableTelemetry() command.

------
   The server generated these startup warnings when booting
   2022-12-11T13:02:33.413+00:00: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem
   2022-12-11T13:02:33.551+00:00: Access control is not enabled for the database. Read and write access to data and configuration is unrestricted
   2022-12-11T13:02:33.551+00:00: You are running this process as the root user, which is not recommended
   2022-12-11T13:02:33.551+00:00: vm.max_map_count is too low
------

------
   Enable MongoDB's free cloud-based monitoring service, which will then receive and display
   metrics about your deployment (disk utilization, CPU, operation statistics, etc).
   
   The monitoring data will be available on a MongoDB website with a unique URL accessible to you
   and anyone you share the URL with. MongoDB may use this information to make product
   improvements and to suggest MongoDB products and deployment options to you.
   
   To enable free monitoring, run the following command: db.enableFreeMonitoring()
   To permanently disable this reminder, run the following command: db.disableFreeMonitoring()
------

test> 

```
All the pods are running: `kubectl get pods`
```
NAME           READY   STATUS    RESTARTS   AGE
auth-mongo-0   2/2     Running   0          79s
auth-mongo-1   2/2     Running   0          72s
```
And my services `kubectl get svc`
```
NAME             TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)     AGE
auth-mongo-srv   ClusterIP   10.99.75.54   <none>        27017/TCP   2m45s
kubernetes       ClusterIP   10.96.0.1     <none>        443/TCP     17d
```

Thanks for you help !

**Comment by jmndao** [comment]
My bad! Little think that I did not pay attention when looking at example like `environment` and `serviceName` which I should have removed from the quotes.
For the environment, I just removed it, and this is what I have:
```
# # Stateful Config
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: notifications-mongo
spec:
  selector:
    matchLabels:
      app: notifications-mongo
  serviceName: notifications-mongo-srv
  replicas: 2
  template:
    metadata:
      labels:
        app: notifications-mongo
        environment: development
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: notifications-mongo
          image: mongo
          command:
            - mongod
          args:
            - "--replSet=rs0"
            - "--bind_ip=0.0.0.0"
          ports:
            - containerPort: 27017
              name: notifications-db
          volumeMounts:
            - name: notifications-pv
              mountPath: /data/notifications-db
        - name: notifications-mongo-sidecar
          image: morphy/k8s-mongo-sidecar
          env:
            - name: KUBERNETES_POD_LABELS
              value: "app=notifications-mongo"
            - name: KUBERNETES_SERVICE_NAME
              value: "notifications-mongo-srv"
      volumes:
        - name: notifications-pv
          persistentVolumeClaim:
            claimName: notifications-pv
  volumeClaimTemplates:
    - metadata:
        name: notifications-pv
      spec:
        accessModes: ["ReadWriteOnce"]
```
