### ISSUE TITLE
No replset config has been received

### ISSUE THREAD

**Issue by wlopez-cl** [morphy2k/k8s-mongo-sidecar#43]
Same as @PuKoren with this yaml file.

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
spec:
  serviceName: mongo
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:4
          command:
            - mongod
          args:
            - '--replSet=rs0'
            - '--bind_ip=0.0.0.0'
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
        - name: mongo-sidecar
          image: morphy/k8s-mongo-sidecar
          env:
            - name: KUBERNETES_POD_LABELS
              value: 'role=mongo, environment=test'
            - name: KUBERNETES_SERVICE_NAME
              value: 'mongo'
  selector:
    matchLabels:
      role: mongo
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: do-block-storage
```

_Originally posted by @wlopez-cl in https://github.com/morphy2k/k8s-mongo-sidecar/issues/1#issuecomment-576428356_
