### ISSUE TITLE
Unable to change service account name via env

### ISSUE THREAD

**Issue by Proger666** [morphy2k/k8s-mongo-sidecar#59]
Kubernetes conf:
```
- name: mongo-sidecar
          image: morphy/k8s-mongo-sidecar
          env:
              - name: KUBERNETES_POD_LABELS
                value: "role=mongo,environment=test"
              - name: KUBERNETES_SERVICE_NAME
                value: "mongo"
```

And in logs i can see that:
`Error in workloop: Error: pods is forbidden: User "system:serviceaccount:default:default" cannot list resource "pods" in API group "" at the cluster scope`

No matter what i put into env variable, sidecar trying to use default acc instead of mongo.
